[tools]
go = "latest"

[tasks]
build = "go build -o gh-aipr"
local = "go build -o gh-aipr && (gh extension remove gh-aipr || true) && gh extension install . && printf \"\\033[32m✓\\033[0m Installed local extension\n\""
prod = "go build -o gh-aipr && (gh extension remove gh-aipr || true) && gh extension install wannabehero/gh-aipr"
